code --install-extension 4ops.terraform
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension boto3typed.boto3-ide
code --install-extension charliermarsh.ruff
code --install-extension christian-kohler.npm-intellisense
code --install-extension docker.docker
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension hashicorp.terraform
code --install-extension hediet.vscode-drawio
code --install-extension inferrinizzard.prettier-sql-vscode
code --install-extension jgclark.vscode-todo-highlight
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-azure-github-copilot
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-bicep
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.pylint
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.datawrangler
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension pjmiravalle.terraform-advanced-syntax-highlighting
code --install-extension pkief.material-icon-theme
code --install-extension ritwickdey.liveserver
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension twxs.cmake
code --install-extension vscodevim.vim
code --install-extension yobson.atom-dark
